version: "3.7"
services:
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "8080:8080"
    depends_on:
      - server
    env_file:
      - ".env"
    volumes:
     - type: bind
       source: ./client
       target: /app
  # client:
  #   container_name: client
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./client
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - server
  #   env_file:
  #     - ".env"
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
    env_file:
      - ".env"
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/store/scripts:/docker-entrypoint-initdb.d

volumes:
  db_data: